### ISSUE TITLE
To fully adopt free software, change license to GPL-2-or-later (IPD proposal)

### ISSUE THREAD

**Issue by ghost** [illumos/ipd#11]
illumos is the free/libre software core SVR4 implementation. Why not use the GPL, so that way SVR4 code can make it's way into Linux? This change will cause collaboration between the Linux kernel team and illumos to go up.

**Comment by rmustacc** [comment]
Hi there, we don't have the legal ability to relicense the vast majority of illumos -- the same way that is the case for the vast majority of the Linux kernel, or other projects without a CLA. The core of illumos has copyright held by an entity which opted to stop distributing it under a public license, which makes any effort here fairly moot, unfortunately.

I don't think this is an area we're going to be able to make progress on and we can't really proceed with a useful IPD here.
